{
    "name": "TMC Partner Fiscal Information Extension",
    "summary": "Add fiscal information to partner",
    "version": "14.0.1.0.0",
    "category": "Contacts",
    "website": "https://www.tmcrosario.gob.ar",
    "author": "Tribunal Municipal de Cuentas - Municipalidad de Rosario",
    "license": "AGPL-3",
    "depends": [],
    "data": ["views/partner.xml"],
    "demo": [],
    "installable": True,
    "application": True,
    "qweb": [],
}  # yapf: disable
